# -*- coding: utf-8 -*-
"""wi_db_add_remark.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AyWs0R9Ax2EB5x1CLcrVseWoPmKOLOc_
"""

### Update WI CSV by HKO DB txt ###
import csv

# Read WI oringinal
with open('/content/text-wi.csv', newline='') as csvfile1:
  rows = csv.reader(csvfile1)

  # Write to new WI
  with open('/content/text-wi-updated.csv', 'w', newline='') as csvfile2:
    writer = csv.writer(csvfile2)

    # Read HKO DB txt
    with open('/content/hko-db.txt', newline='') as hko:
      signals = list(csv.reader(hko,delimiter='	'))

      # Main logic
      count=0
      line=0
      print_remark=0

      for row in rows:
        #print("outter loop",row)
        line+=1  
        if line%100000 == 0 :
          print("Processing ", line, " at ", row[0])   

        for signal in signals:
          #print("inter loop",signal)
          count+=1
          start_time = signal[3].replace("/","-") + " " + signal[4] + ":00"
          end_time   = signal[5].replace("/","-") + " " + signal[6] + ":00"
          #print(start_time,"<=",row[0]," AND ",end_time,">=",row[0])
          if start_time <= row[0] and end_time >= row[0] :
            print_remark=1
            break            
          else:
            print_remark=0  
   
        if print_remark==1 :
          remark = signal[0] + signal[1] + " " + signal[2].replace(" ","號") + "訊號生效" 
          writer.writerow([row[0],row[1],remark])
        else:
          writer.writerow([row[0],row[1],""])       

    print("Total calculation: ",count)